name: Bug Report
description: File a bug report.
title: "bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: |
        After I did X1, X2 and X3, Y happened. I expected Z.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: |
        Please provide a minimal reproduction of the bug.
      placeholder: |
        Step1: do X
        Step2: do Y
        Step3: do Z and the bug happens
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of the software are you using?
      value: |
        hexo: x.x.x
        hexon: x.x.x
        your-hexo-theme: your-theme@x.x.x
  - type: checkboxes
    id: before-submit
    attributes:
      label: Before you submit
      description: |
        Please check the following
      options:
        - label: I have included version information
          required: true